"""Domain marketplace transfer & escrow enums."""

from __future__ import annotations

from enum import Enum


class MarketplaceEscrowStatus(str, Enum):
    HELD = "HELD"
    RELEASED = "RELEASED"
    REFUNDED = "REFUNDED"


class MarketplaceTransferStatus(str, Enum):
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    AWAITING_AUTH_CODE = "AWAITING_AUTH_CODE"
    AUTH_CODE_AVAILABLE = "AUTH_CODE_AVAILABLE"
    AUTH_CODE_RECEIVED = "AUTH_CODE_RECEIVED"
    AUTH_CODE_VIEWED = "AUTH_CODE_VIEWED"
    TRANSFER_IN_PROGRESS = "TRANSFER_IN_PROGRESS"
    TRANSFER_COMPLETED = "TRANSFER_COMPLETED"
    PAYOUT_PENDING = "PAYOUT_PENDING"
    PAYOUT_APPROVED = "PAYOUT_APPROVED"
    PAYOUT_RELEASED = "PAYOUT_RELEASED"
    COMPLETED = "COMPLETED"
    SELLER_PAID = "SELLER_PAID"
    AUTH_CODE_TIMEOUT = "AUTH_CODE_TIMEOUT"
    ADMIN_REVIEW_REQUIRED = "ADMIN_REVIEW_REQUIRED"
    BUYER_TRANSFER_TIMEOUT = "BUYER_TRANSFER_TIMEOUT"
    REFUNDED = "REFUNDED"
    DISPUTED = "DISPUTED"
    CANCELLED = "CANCELLED"


class TransferMethod(str, Enum):
    SELF = "SELF"
    COBROTHER_ASSISTED = "COBROTHER_ASSISTED"


class TransferDisputeStatus(str, Enum):
    NONE = "NONE"
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED_REFUND = "RESOLVED_REFUND"
    RESOLVED_PAYOUT = "RESOLVED_PAYOUT"
    CLOSED = "CLOSED"


class DisputeReason(str, Enum):
    INVALID_AUTH_CODE = "INVALID_AUTH_CODE"
    SELLER_UNRESPONSIVE = "SELLER_UNRESPONSIVE"
    TRANSFER_ISSUE = "TRANSFER_ISSUE"


class TransferVerifiedBy(str, Enum):
    BUYER = "BUYER"
    ADMIN = "ADMIN"


class TransferEventType(str, Enum):
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    AUTH_SUBMITTED = "AUTH_SUBMITTED"
    OTP_REVEAL = "OTP_REVEAL"
    TRANSFER_STARTED = "TRANSFER_STARTED"
    TRANSFER_CONFIRMED = "TRANSFER_CONFIRMED"
    ASSISTANCE_REQUESTED = "ASSISTANCE_REQUESTED"
    ADMIN_REVIEW = "ADMIN_REVIEW"
    PAYOUT_PENDING = "PAYOUT_PENDING"
    PAYOUT_APPROVED = "PAYOUT_APPROVED"
    PAYOUT_REMINDER_SENT = "PAYOUT_REMINDER_SENT"
    PAYOUT_RELEASED = "PAYOUT_RELEASED"
    REFUNDED = "REFUNDED"
    DISPUTE_OPENED = "DISPUTE_OPENED"
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED"
    WHOIS_CHECK = "WHOIS_CHECK"


class SellerKycStatus(str, Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class PayoutMethod(str, Enum):
    BANK_ACCOUNT = "BANK_ACCOUNT"
    UPI = "UPI"


class SellerPayoutStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    SENT = "SENT"
    FAILED = "FAILED"
