"""Add technology marketplace fields and pricing plans

Revision ID: 7f3e7e682dc7
Revises: b1c2d3e4f5a6
Create Date: 2026-06-27 12:33:19.762549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f3e7e682dc7'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
technology_type_enum = postgresql.ENUM(
    "SOFTWARE",
    "HARDWARE",
    name="technology_type_enum",
    create_type=False,
)

technology_pricing_plan_duration_enum = postgresql.ENUM(
    "ONE_TIME",
    "ONE_MONTH",
    "THREE_MONTHS",
    "SIX_MONTHS",
    "TWELVE_MONTHS",
    name="technology_pricing_plan_duration_enum",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    technology_type_enum.create(bind, checkfirst=True)
    technology_pricing_plan_duration_enum.create(bind, checkfirst=True)
    op.create_table('software_pricing_plans',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('plan_duration', technology_pricing_plan_duration_enum, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['software_listings.id'], name=op.f('fk_software_pricing_plans_listing_id_software_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_software_pricing_plans'))
    )
    op.create_index('idx_software_pricing_plans_listing_id', 'software_pricing_plans', ['listing_id'], unique=False)
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_creator_follows_community_id'), table_name='creator_follows')
    op.drop_index(op.f('ix_creator_follows_follower_user_id'), table_name='creator_follows')
    op.drop_table('creator_follows')
    op.drop_index(op.f('idx_auction_participation_lookup'), table_name='auction_participations')
    op.drop_table('auction_participations')
    op.drop_index(op.f('idx_auction_fee_payments_order'), table_name='auction_fee_payments')
    op.drop_index(op.f('idx_auction_fee_payments_user_kind'), table_name='auction_fee_payments')
    op.drop_table('auction_fee_payments')
    op.alter_column('agreement', 'terms',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('ai_analytics_events', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('ai_analytics_events', sa.Column('prompt', sa.Text(), nullable=True))
    op.add_column('ai_analytics_events', sa.Column('input_mode', sa.String(), nullable=False))
    op.add_column('ai_analytics_events', sa.Column('assistant_mode', sa.String(), nullable=False))
    op.add_column('ai_analytics_events', sa.Column('categories', sa.JSON(), nullable=False))
    op.add_column('ai_analytics_events', sa.Column('metadata', sa.JSON(), nullable=False))
    op.alter_column('auctions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'EXTENDED', 'ENDED', 'UNSOLD', 'CANCELLED', 'PAYMENT_PENDING', 'COMPLETED', name='auction_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auctions', 'total_bids',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auctions', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auctions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auctions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('auctions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('be_cobrother_applications', 'equipment',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('be_cobrother_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('be_cobrother_applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bids', 'is_winning_bid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bids', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bids', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bids', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_co_ventures_applicant_user_id', 'co_ventures', ['applicant_user_id'], unique=False)
    op.create_index('idx_co_ventures_venture_id', 'co_ventures', ['venture_id'], unique=False)
    op.create_index('idx_cobrother_requests_assignee', 'cobrother_requests', ['assigned_cobrother_id'], unique=False)
    op.create_index('idx_cobrother_requests_entity', 'cobrother_requests', ['request_type', 'entity_id'], unique=False)
    op.drop_constraint(op.f('fk_cobrother_requests_admin_user_id_users'), 'cobrother_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_cobrother_requests_assigned_cobrother_id_users'), 'cobrother_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cobrother_requests_admin_user_id_users'), 'cobrother_requests', 'users', ['admin_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_cobrother_requests_assigned_cobrother_id_users'), 'cobrother_requests', 'users', ['assigned_cobrother_id'], ['id'], ondelete='SET NULL')
    op.alter_column('community', 'views',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('community', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('community', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('community', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_community_id'), table_name='community')
    op.alter_column('community_auctions', 'winner_payment_paid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('community_auctions', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_disputes', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_enquiries', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_listings', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_listings', 'views',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_listings', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_listings', 'verification_status',
               existing_type=postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', 'MORE_INFO_REQUESTED', name='domain_listing_verification_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_listings', 'taken_down',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_listings', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_listings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_domain_listings_listed_by', 'domain_listings', ['listed_by_user_id'], unique=False)
    op.create_index('idx_domain_listings_name', 'domain_listings', ['domain_name'], unique=False)
    op.drop_constraint(op.f('fk_domain_listings_listed_by_user_id_users'), 'domain_listings', type_='foreignkey')
    op.drop_constraint(op.f('fk_domain_listings_contact_info_id_contact_info'), 'domain_listings', type_='foreignkey')
    op.drop_constraint(op.f('fk_domain_listings_agreement_id_agreement'), 'domain_listings', type_='foreignkey')
    op.drop_constraint(op.f('fk_domain_listings_purchased_by_user_id_users'), 'domain_listings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_domain_listings_listed_by_user_id_users'), 'domain_listings', 'users', ['listed_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_domain_listings_contact_info_id_contact_info'), 'domain_listings', 'contact_info', ['contact_info_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_domain_listings_purchased_by_user_id_users'), 'domain_listings', 'users', ['purchased_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_domain_listings_agreement_id_agreement'), 'domain_listings', 'agreement', ['agreement_id'], ['id'], ondelete='SET NULL')
    op.alter_column('domain_marketplace_transactions', 'platform_fee_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'escrow_status',
               existing_type=postgresql.ENUM('HELD', 'RELEASED', 'REFUNDED', name='marketplace_escrow_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'transfer_status',
               existing_type=postgresql.ENUM('PAYMENT_COMPLETED', 'AWAITING_AUTH_CODE', 'AUTH_CODE_RECEIVED', 'AUTH_CODE_VIEWED', 'TRANSFER_IN_PROGRESS', 'TRANSFER_COMPLETED', 'PAYOUT_PENDING', 'SELLER_PAID', 'AUTH_CODE_TIMEOUT', 'ADMIN_REVIEW_REQUIRED', 'BUYER_TRANSFER_TIMEOUT', 'REFUNDED', 'DISPUTED', 'CANCELLED', 'AUTH_CODE_AVAILABLE', 'PAYOUT_APPROVED', 'PAYOUT_RELEASED', 'COMPLETED', name='marketplace_transfer_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'auth_code_key_version',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'payout_reminder_count',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'dispute_status',
               existing_type=postgresql.ENUM('NONE', 'OPEN', 'UNDER_REVIEW', 'RESOLVED_REFUND', 'RESOLVED_PAYOUT', 'CLOSED', name='transfer_dispute_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_sale_seller_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_sale_buyer_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_seller_reminder_12h_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_seller_reminder_6h_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_auth_available_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_buyer_reminder_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_admin_review_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_payout_released_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_refund_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'provision_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'transfer_status',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'renewal_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'registrar_lock',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'whois_privacy',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'icann_verification_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'auto_renew_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_receipt_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_submitted_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_active_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_raa_pending_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_failed_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_domain_reg_orders_buyer', 'domain_registration_orders', ['buyer_id'], unique=False)
    op.create_index('idx_domain_reg_orders_rzp_order', 'domain_registration_orders', ['razorpay_order_id'], unique=False)
    op.create_index('idx_domain_reg_orders_status', 'domain_registration_orders', ['status'], unique=False)
    op.drop_constraint(op.f('fk_domain_registration_orders_buyer_id_users'), 'domain_registration_orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_domain_registration_orders_buyer_id_users'), 'domain_registration_orders', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('domains', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('domains', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('uq_domains_domain_name_active'), table_name='domains', postgresql_where='(NOT is_deleted)')
    op.create_index(op.f('ix_domains_owner_id'), 'domains', ['owner_id'], unique=False)
    op.alter_column('meeting_schedules', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('meeting_schedules', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_meeting_schedules_lister_id'), table_name='meeting_schedules')
    op.alter_column('operations_service_requests', 'quoted_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operations_service_requests', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operations_services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operations_services', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operations_services', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operations_services', 'service_type',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operations_services', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_operations_services_service_type'), table_name='operations_services')
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'payment_status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_payments_razorpay_order_id'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.drop_index(op.f('ix_seller_payout_profile_audit_user_created'), table_name='seller_payout_profile_audit_events')
    op.alter_column('seller_payout_profiles', 'kyc_status',
               existing_type=postgresql.ENUM('PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='seller_kyc_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('seller_payout_profiles', 'is_complete',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('seller_payout_profiles', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('seller_payouts', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'SENT', 'FAILED', name='seller_payout_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_auction_bids', 'is_winning_bid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_auction_participations', 'status',
               existing_type=postgresql.ENUM('CREATED', 'COMPLETED', 'FAILED', name='software_auction_participation_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_auctions', 'current_highest_bid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_auctions', 'total_bids',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_auctions', 'source_code_included',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_auctions', 'support_included',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_auctions', 'support_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_auctions', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('software_listings', sa.Column('documentation_urls', sa.Text(), nullable=True))
    op.add_column('software_listings', sa.Column('download_urls', sa.Text(), nullable=True))
    op.add_column(
    "software_listings",
    sa.Column(
        "technology_type",
        technology_type_enum,   #
        nullable=False,
        server_default="SOFTWARE",
    ),
)
    op.alter_column('software_listings', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_listings', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_listings', 'views',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_listings', 'taken_down',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_listings', 'official',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_listings', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_listings', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_listings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_software_listings_listed_by', 'software_listings', ['listed_by_user_id'], unique=False)
    op.create_index('idx_software_listings_name', 'software_listings', ['name'], unique=False)
    op.drop_constraint(op.f('fk_software_listings_agreement_id_agreement'), 'software_listings', type_='foreignkey')
    op.drop_constraint(op.f('fk_software_listings_listed_by_user_id_users'), 'software_listings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_software_listings_agreement_id_agreement'), 'software_listings', 'agreement', ['agreement_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_software_listings_listed_by_user_id_users'), 'software_listings', 'users', ['listed_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('software_purchases', sa.Column('payout_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('software_purchases', sa.Column('payout_reminder_count', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('software_purchases', sa.Column('selected_plan',technology_pricing_plan_duration_enum, nullable=True))
    op.add_column('software_purchases', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('software_purchases', sa.Column('expiry_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('software_purchases', 'completion_status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', name='software_purchase_completion_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_purchases', 'co_brother_opt_in',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_purchases', 'co_brother_help_paid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_software_purchases_buyer', 'software_purchases', ['buyer_id'], unique=False)
    op.create_index('idx_software_purchases_rzp_order', 'software_purchases', ['razorpay_order_id'], unique=False)
    op.alter_column('transactions', 'transaction_status',
               existing_type=postgresql.ENUM('INITIATED', 'SUCCESS', 'FAILED', 'VERIFIED', name='transaction_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_company_profile_documents', 'visibility',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_company_profile_documents', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_company_profile_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_company_profile_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_venture_company_profile_documents_profile_id'), table_name='venture_company_profile_documents')
    op.alter_column('venture_company_profiles', 'is_complete',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_company_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_company_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_venture_company_profiles_venture_id'), table_name='venture_company_profiles')
    op.drop_index(op.f('idx_venture_documents_venture_id'), table_name='venture_documents')
    op.create_index(op.f('ix_venture_documents_venture_id'), 'venture_documents', ['venture_id'], unique=False)
    op.alter_column('venture_pitches', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SELLER_ACCEPTED', 'SELLER_REJECTED', 'CANCELLED', 'COMPLETED', 'SHORTLISTED', 'DEAL_SELECTED', name='venture_acquisition_application_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_pitches', 'source',
               existing_type=postgresql.ENUM('REGULAR_APPLY', 'AUCTION_WINNER', name='venture_acquisition_application_source_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_pitches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_pitches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_roles', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_venture_roles_venture_id', 'venture_roles', ['venture_id'], unique=False)
    op.alter_column('venture_verification_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture_verification_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'views',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'co_venture_application_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'taken_down',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'gstin_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'verification_requested',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'verification_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               type_=sa.Enum('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='venture_verification_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('ventures', 'listing_approval_status',
               existing_type=postgresql.ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'DRAFT', name='venture_listing_approval_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ventures', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_ventures_sale_type', 'ventures', ['sale_type'], unique=False)
    op.create_index('idx_ventures_stage', 'ventures', ['stage'], unique=False)
    op.create_index(op.f('ix_ventures_listed_by_user_id'), 'ventures', ['listed_by_user_id'], unique=False)
    op.drop_constraint(op.f('fk_ventures_listed_by_user_id_users'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_contact_info_id_contact_info'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_purchased_by_user_id_users'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_brand_details_id_brand_details'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_agreement_id_agreement'), 'ventures', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ventures_agreement_id_agreement'), 'ventures', 'agreement', ['agreement_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_ventures_purchased_by_user_id_users'), 'ventures', 'users', ['purchased_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_ventures_listing_approved_by_user_id_users'), 'ventures', 'users', ['listing_approved_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_ventures_brand_details_id_brand_details'), 'ventures', 'brand_details', ['brand_details_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_ventures_contact_info_id_contact_info'), 'ventures', 'contact_info', ['contact_info_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_ventures_listed_by_user_id_users'), 'ventures', 'users', ['listed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ventures_listed_by_user_id_users'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_contact_info_id_contact_info'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_brand_details_id_brand_details'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_listing_approved_by_user_id_users'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_purchased_by_user_id_users'), 'ventures', type_='foreignkey')
    op.drop_constraint(op.f('fk_ventures_agreement_id_agreement'), 'ventures', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ventures_agreement_id_agreement'), 'ventures', 'agreement', ['agreement_id'], ['id'])
    op.create_foreign_key(op.f('fk_ventures_brand_details_id_brand_details'), 'ventures', 'brand_details', ['brand_details_id'], ['id'])
    op.create_foreign_key(op.f('fk_ventures_purchased_by_user_id_users'), 'ventures', 'users', ['purchased_by_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_ventures_contact_info_id_contact_info'), 'ventures', 'contact_info', ['contact_info_id'], ['id'])
    op.create_foreign_key(op.f('fk_ventures_listed_by_user_id_users'), 'ventures', 'users', ['listed_by_user_id'], ['id'])
    op.drop_index(op.f('ix_ventures_listed_by_user_id'), table_name='ventures')
    op.drop_index('idx_ventures_stage', table_name='ventures')
    op.drop_index('idx_ventures_sale_type', table_name='ventures')
    op.alter_column('ventures', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ventures', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ventures', 'listing_approval_status',
               existing_type=postgresql.ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'DRAFT', name='venture_listing_approval_status_enum'),
               server_default=sa.text("'PENDING_APPROVAL'::venture_listing_approval_status_enum"),
               existing_nullable=False)
    op.alter_column('ventures', 'verification_status',
               existing_type=sa.Enum('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='venture_verification_status_enum', native_enum=False),
               server_default=sa.text("'NONE'::character varying"),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('ventures', 'verification_requested',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ventures', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ventures', 'gstin_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ventures', 'taken_down',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ventures', 'co_venture_application_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('ventures', 'views',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('ventures', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('venture_verification_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('venture_verification_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_venture_roles_venture_id', table_name='venture_roles')
    op.alter_column('venture_roles', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('venture_pitches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('venture_pitches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('venture_pitches', 'source',
               existing_type=postgresql.ENUM('REGULAR_APPLY', 'AUCTION_WINNER', name='venture_acquisition_application_source_enum'),
               server_default=sa.text("'REGULAR_APPLY'::venture_acquisition_application_source_enum"),
               existing_nullable=False)
    op.alter_column('venture_pitches', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SELLER_ACCEPTED', 'SELLER_REJECTED', 'CANCELLED', 'COMPLETED', 'SHORTLISTED', 'DEAL_SELECTED', name='venture_acquisition_application_status_enum'),
               server_default=sa.text("'PENDING'::venture_acquisition_application_status_enum"),
               existing_nullable=False)
    op.drop_index(op.f('ix_venture_documents_venture_id'), table_name='venture_documents')
    op.create_index(op.f('idx_venture_documents_venture_id'), 'venture_documents', ['venture_id'], unique=False)
    op.create_index(op.f('idx_venture_company_profiles_venture_id'), 'venture_company_profiles', ['venture_id'], unique=False)
    op.alter_column('venture_company_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('venture_company_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('venture_company_profiles', 'is_complete',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('idx_venture_company_profile_documents_profile_id'), 'venture_company_profile_documents', ['profile_id'], unique=False)
    op.alter_column('venture_company_profile_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('venture_company_profile_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('venture_company_profile_documents', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('venture_company_profile_documents', 'visibility',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'PUBLIC'::character varying"),
               existing_nullable=False)
    op.alter_column('transactions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_status',
               existing_type=postgresql.ENUM('INITIATED', 'SUCCESS', 'FAILED', 'VERIFIED', name='transaction_status_enum'),
               server_default=sa.text("'INITIATED'::transaction_status_enum"),
               existing_nullable=False)
    op.drop_index('idx_software_purchases_rzp_order', table_name='software_purchases')
    op.drop_index('idx_software_purchases_buyer', table_name='software_purchases')
    op.alter_column('software_purchases', 'co_brother_help_paid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_purchases', 'co_brother_opt_in',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_purchases', 'completion_status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', name='software_purchase_completion_status_enum'),
               server_default=sa.text("'PENDING'::software_purchase_completion_status_enum"),
               existing_nullable=False)
    op.drop_column('software_purchases', 'expiry_reminder_sent_at')
    op.drop_column('software_purchases', 'expiry_date')
    op.drop_column('software_purchases', 'selected_plan')
    op.drop_column('software_purchases', 'payout_reminder_count')
    op.drop_column('software_purchases', 'payout_reminder_sent_at')
    op.drop_constraint(op.f('fk_software_listings_listed_by_user_id_users'), 'software_listings', type_='foreignkey')
    op.drop_constraint(op.f('fk_software_listings_agreement_id_agreement'), 'software_listings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_software_listings_listed_by_user_id_users'), 'software_listings', 'users', ['listed_by_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_software_listings_agreement_id_agreement'), 'software_listings', 'agreement', ['agreement_id'], ['id'])
    op.drop_index('idx_software_listings_name', table_name='software_listings')
    op.drop_index('idx_software_listings_listed_by', table_name='software_listings')
    op.alter_column('software_listings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_listings', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_listings', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_listings', 'official',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_listings', 'taken_down',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_listings', 'views',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('software_listings', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('software_listings', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('software_listings', 'technology_type')
    op.drop_column('software_listings', 'download_urls')
    op.drop_column('software_listings', 'documentation_urls')
    op.alter_column('software_auctions', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_auctions', 'support_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('software_auctions', 'support_included',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_auctions', 'source_code_included',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('software_auctions', 'total_bids',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('software_auctions', 'current_highest_bid',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('software_auction_participations', 'status',
               existing_type=postgresql.ENUM('CREATED', 'COMPLETED', 'FAILED', name='software_auction_participation_status_enum'),
               server_default=sa.text("'CREATED'::software_auction_participation_status_enum"),
               existing_nullable=False)
    op.alter_column('software_auction_bids', 'is_winning_bid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('seller_payouts', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'SENT', 'FAILED', name='seller_payout_status_enum'),
               server_default=sa.text("'PENDING'::seller_payout_status_enum"),
               existing_nullable=False)
    op.alter_column('seller_payout_profiles', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('seller_payout_profiles', 'is_complete',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('seller_payout_profiles', 'kyc_status',
               existing_type=postgresql.ENUM('PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='seller_kyc_status_enum'),
               server_default=sa.text("'PENDING'::seller_kyc_status_enum"),
               existing_nullable=False)
    op.create_index(op.f('ix_seller_payout_profile_audit_user_created'), 'seller_payout_profile_audit_events', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_unique_constraint(op.f('uq_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'])
    op.alter_column('payments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('payments', 'payment_status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum'),
               server_default=sa.text("'PENDING'::payment_status_enum"),
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('idx_operations_services_service_type'), 'operations_services', ['service_type'], unique=False)
    op.alter_column('operations_services', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('operations_services', 'service_type',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'virtual_assistance'::character varying"),
               existing_nullable=False)
    op.alter_column('operations_services', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('operations_services', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('operations_services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('operations_service_requests', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('operations_service_requests', 'quoted_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.create_index(op.f('ix_meeting_schedules_lister_id'), 'meeting_schedules', ['lister_id'], unique=False)
    op.alter_column('meeting_schedules', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('meeting_schedules', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.drop_index(op.f('ix_domains_owner_id'), table_name='domains')
    op.create_index(op.f('uq_domains_domain_name_active'), 'domains', [sa.literal_column('lower(domain_name::text)')], unique=True, postgresql_where='(NOT is_deleted)')
    op.alter_column('domains', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('domains', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_domain_registration_orders_buyer_id_users'), 'domain_registration_orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_domain_registration_orders_buyer_id_users'), 'domain_registration_orders', 'users', ['buyer_id'], ['id'])
    op.drop_index('idx_domain_reg_orders_status', table_name='domain_registration_orders')
    op.drop_index('idx_domain_reg_orders_rzp_order', table_name='domain_registration_orders')
    op.drop_index('idx_domain_reg_orders_buyer', table_name='domain_registration_orders')
    op.alter_column('domain_registration_orders', 'email_failed_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_raa_pending_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_active_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_submitted_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'email_receipt_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'auto_renew_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'icann_verification_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'UNKNOWN'::character varying"),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'whois_privacy',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'registrar_lock',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'renewal_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'transfer_status',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'NONE'::character varying"),
               existing_nullable=False)
    op.alter_column('domain_registration_orders', 'provision_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_refund_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_payout_released_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_admin_review_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_buyer_reminder_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_auth_available_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_seller_reminder_6h_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_seller_reminder_12h_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_sale_buyer_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'email_sale_seller_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'dispute_status',
               existing_type=postgresql.ENUM('NONE', 'OPEN', 'UNDER_REVIEW', 'RESOLVED_REFUND', 'RESOLVED_PAYOUT', 'CLOSED', name='transfer_dispute_status_enum'),
               server_default=sa.text("'NONE'::transfer_dispute_status_enum"),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'payout_reminder_count',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'0'::smallint"),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'auth_code_key_version',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'1'::smallint"),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'transfer_status',
               existing_type=postgresql.ENUM('PAYMENT_COMPLETED', 'AWAITING_AUTH_CODE', 'AUTH_CODE_RECEIVED', 'AUTH_CODE_VIEWED', 'TRANSFER_IN_PROGRESS', 'TRANSFER_COMPLETED', 'PAYOUT_PENDING', 'SELLER_PAID', 'AUTH_CODE_TIMEOUT', 'ADMIN_REVIEW_REQUIRED', 'BUYER_TRANSFER_TIMEOUT', 'REFUNDED', 'DISPUTED', 'CANCELLED', 'AUTH_CODE_AVAILABLE', 'PAYOUT_APPROVED', 'PAYOUT_RELEASED', 'COMPLETED', name='marketplace_transfer_status_enum'),
               server_default=sa.text("'AWAITING_AUTH_CODE'::marketplace_transfer_status_enum"),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'escrow_status',
               existing_type=postgresql.ENUM('HELD', 'RELEASED', 'REFUNDED', name='marketplace_escrow_status_enum'),
               server_default=sa.text("'HELD'::marketplace_escrow_status_enum"),
               existing_nullable=False)
    op.alter_column('domain_marketplace_transactions', 'platform_fee_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_domain_listings_agreement_id_agreement'), 'domain_listings', type_='foreignkey')
    op.drop_constraint(op.f('fk_domain_listings_purchased_by_user_id_users'), 'domain_listings', type_='foreignkey')
    op.drop_constraint(op.f('fk_domain_listings_contact_info_id_contact_info'), 'domain_listings', type_='foreignkey')
    op.drop_constraint(op.f('fk_domain_listings_listed_by_user_id_users'), 'domain_listings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_domain_listings_purchased_by_user_id_users'), 'domain_listings', 'users', ['purchased_by_user_id'], ['id'])
    op.create_foreign_key(op.f('fk_domain_listings_agreement_id_agreement'), 'domain_listings', 'agreement', ['agreement_id'], ['id'])
    op.create_foreign_key(op.f('fk_domain_listings_contact_info_id_contact_info'), 'domain_listings', 'contact_info', ['contact_info_id'], ['id'])
    op.create_foreign_key(op.f('fk_domain_listings_listed_by_user_id_users'), 'domain_listings', 'users', ['listed_by_user_id'], ['id'])
    op.drop_index('idx_domain_listings_name', table_name='domain_listings')
    op.drop_index('idx_domain_listings_listed_by', table_name='domain_listings')
    op.alter_column('domain_listings', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_listings', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_listings', 'taken_down',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_listings', 'verification_status',
               existing_type=postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', 'MORE_INFO_REQUESTED', name='domain_listing_verification_status_enum'),
               server_default=sa.text("'PENDING'::domain_listing_verification_status_enum"),
               existing_nullable=False)
    op.alter_column('domain_listings', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('domain_listings', 'views',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('domain_listings', 'status',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('domain_enquiries', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('domain_disputes', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'OPEN'::character varying"),
               existing_nullable=False)
    op.alter_column('community_auctions', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('community_auctions', 'winner_payment_paid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('ix_community_id'), 'community', ['id'], unique=False)
    op.alter_column('community', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('community', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('community', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('community', 'views',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_cobrother_requests_assigned_cobrother_id_users'), 'cobrother_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_cobrother_requests_admin_user_id_users'), 'cobrother_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cobrother_requests_assigned_cobrother_id_users'), 'cobrother_requests', 'users', ['assigned_cobrother_id'], ['id'])
    op.create_foreign_key(op.f('fk_cobrother_requests_admin_user_id_users'), 'cobrother_requests', 'users', ['admin_user_id'], ['id'])
    op.drop_index('idx_cobrother_requests_entity', table_name='cobrother_requests')
    op.drop_index('idx_cobrother_requests_assignee', table_name='cobrother_requests')
    op.drop_index('idx_co_ventures_venture_id', table_name='co_ventures')
    op.drop_index('idx_co_ventures_applicant_user_id', table_name='co_ventures')
    op.alter_column('bids', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('bids', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('bids', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('bids', 'is_winning_bid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('be_cobrother_applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('be_cobrother_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('be_cobrother_applications', 'equipment',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('auctions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('auctions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('auctions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('auctions', 'featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('auctions', 'total_bids',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('auctions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'EXTENDED', 'ENDED', 'UNSOLD', 'CANCELLED', 'PAYMENT_PENDING', 'COMPLETED', name='auction_status_enum'),
               server_default=sa.text("'DRAFT'::auction_status_enum"),
               existing_nullable=False)
    op.drop_column('ai_analytics_events', 'metadata')
    op.drop_column('ai_analytics_events', 'categories')
    op.drop_column('ai_analytics_events', 'assistant_mode')
    op.drop_column('ai_analytics_events', 'input_mode')
    op.drop_column('ai_analytics_events', 'prompt')
    op.drop_column('ai_analytics_events', 'session_id')
    op.alter_column('agreement', 'terms',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_table('auction_fee_payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_kind', postgresql.ENUM('CREATION', 'BID', name='auction_fee_payment_kind_enum'), autoincrement=False, nullable=False),
    sa.Column('auction_type', postgresql.ENUM('DOMAIN', 'SOFTWARE', 'COMMUNITY', name='auction_fee_auction_type_enum'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('auction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('bid_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('fee_amount_inr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('razorpay_payment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('CREATED', 'COMPLETED', 'CONSUMED', name='auction_fee_payment_status_enum'), server_default=sa.text("'CREATED'::auction_fee_payment_status_enum"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auction_fee_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auction_fee_payments')),
    sa.UniqueConstraint('razorpay_order_id', name=op.f('uq_auction_fee_payments_order'))
    )
    op.create_index(op.f('idx_auction_fee_payments_user_kind'), 'auction_fee_payments', ['user_id', 'payment_kind'], unique=False)
    op.create_index(op.f('idx_auction_fee_payments_order'), 'auction_fee_payments', ['razorpay_order_id'], unique=False)
    op.create_table('auction_participations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('auction_type', postgresql.ENUM('DOMAIN', 'SOFTWARE', 'COMMUNITY', name='auction_participation_type_enum'), autoincrement=False, nullable=False),
    sa.Column('auction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fee_amount_inr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('razorpay_payment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('CREATED', 'COMPLETED', 'FAILED', name='auction_participation_status_enum'), server_default=sa.text("'CREATED'::auction_participation_status_enum"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auction_participations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('auction_participations_pkey')),
    sa.UniqueConstraint('auction_type', 'auction_id', 'user_id', name=op.f('uq_auction_participations_type_auction_user'))
    )
    op.create_index(op.f('idx_auction_participation_lookup'), 'auction_participations', ['auction_type', 'auction_id', 'user_id'], unique=False)
    op.create_table('creator_follows',
    sa.Column('follower_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('community_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name=op.f('fk_creator_follows_community_id_community')),
    sa.ForeignKeyConstraint(['follower_user_id'], ['users.id'], name=op.f('fk_creator_follows_follower_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creator_follows')),
    sa.UniqueConstraint('follower_user_id', 'community_id', name=op.f('uq_creator_follow_user_community'))
    )
    op.create_index(op.f('ix_creator_follows_follower_user_id'), 'creator_follows', ['follower_user_id'], unique=False)
    op.create_index(op.f('ix_creator_follows_community_id'), 'creator_follows', ['community_id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('setting_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('setting_key', name=op.f('pk_platform_settings'))
    )
    op.drop_index('idx_software_pricing_plans_listing_id', table_name='software_pricing_plans')
    op.drop_table('software_pricing_plans')

    technology_pricing_plan_duration_enum.drop(op.get_bind(), checkfirst=True)
    technology_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
