"""recreate auction_fee_payments table

Revision ID: 7e125ff2f3ee
Revises: da1616ed8692
Create Date: 2026-06-30 12:30:16.182727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e125ff2f3ee'
down_revision: Union[str, Sequence[str], None] = 'da1616ed8692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_fee_payments',
    sa.Column('payment_kind', postgresql.ENUM('CREATION', 'BID', name='auction_fee_payment_kind_enum', create_type=False), nullable=False),
    sa.Column('auction_type', postgresql.ENUM('DOMAIN', 'SOFTWARE', 'COMMUNITY', name='auction_fee_auction_type_enum', create_type=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('bid_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fee_amount_inr', sa.Float(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('status', postgresql.ENUM('CREATED', 'COMPLETED', 'CONSUMED', name='auction_fee_payment_status_enum', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auction_fee_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auction_fee_payments')),
    sa.UniqueConstraint('razorpay_order_id', name='uq_auction_fee_payments_order')
    )
    op.create_index('idx_auction_fee_payments_order', 'auction_fee_payments', ['razorpay_order_id'], unique=False)
    op.create_index('idx_auction_fee_payments_user_kind', 'auction_fee_payments', ['user_id', 'payment_kind'], unique=False)
    op.drop_table('platform_settings')
    op.alter_column('seller_payouts', 'transaction_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('software_listings', 'technology_type',
               existing_type=postgresql.ENUM('SOFTWARE', 'HARDWARE', name='technology_type_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_purchases', 'gross_amount_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_purchases', 'platform_fee_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_purchases', 'seller_payout_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('software_purchases', 'payout_reminder_count',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('software_purchases', 'payout_reminder_count',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'0'::smallint"),
               existing_nullable=False)
    op.alter_column('software_purchases', 'seller_payout_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('software_purchases', 'platform_fee_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('software_purchases', 'gross_amount_inr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('software_listings', 'technology_type',
               existing_type=postgresql.ENUM('SOFTWARE', 'HARDWARE', name='technology_type_enum'),
               server_default=sa.text("'SOFTWARE'::technology_type_enum"),
               existing_nullable=False)
    op.alter_column('seller_payouts', 'transaction_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('platform_settings',
    sa.Column('setting_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('setting_key', name=op.f('platform_settings_pkey'))
    )
    op.drop_index('idx_auction_fee_payments_user_kind', table_name='auction_fee_payments')
    op.drop_index('idx_auction_fee_payments_order', table_name='auction_fee_payments')
    op.drop_table('auction_fee_payments')
    # ### end Alembic commands ###
