"""create_co_venture_table

Revision ID: 673e28543ac5
Revises: e8f9a0b1c234
Create Date: 2026-05-19 16:46:34.502672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '673e28543ac5'
down_revision: Union[str, Sequence[str], None] = 'e8f9a0b1c234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venture', 'co_venture_application_count',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('venture', 'sale_type',
               existing_type=postgresql.ENUM('REGULAR', 'AUCTION', name='venture_sale_type_enum'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venture', 'sale_type',
               existing_type=postgresql.ENUM('REGULAR', 'AUCTION', name='venture_sale_type_enum'),
               server_default=sa.text("'REGULAR'::venture_sale_type_enum"),
               existing_nullable=False)
    op.alter_column('venture', 'co_venture_application_count',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
