"""add_edge_points_history_and_referral_tracks

Revision ID: bc2a24942095
Revises: 25ad6fabcb80
Create Date: 2026-07-10 12:30:03.967061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc2a24942095'
down_revision: Union[str, Sequence[str], None] = '25ad6fabcb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_points_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('REFERRAL_EARN', 'CHECKOUT_REDEEM', 'REDEEM_REVERT', name='edge_points_transaction_type_enum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_edge_points_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge_points_history'))
    )
    op.create_index(op.f('ix_edge_points_history_user_id'), 'edge_points_history', ['user_id'], unique=False)
    op.create_table('referral_tracks',
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('listing_type', sa.String(length=50), nullable=False),
    sa.Column('visitor_ip', sa.String(length=45), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('fk_referral_tracks_referrer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['users.id'], name=op.f('fk_referral_tracks_visitor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_tracks'))
    )
    op.create_index(op.f('ix_referral_tracks_listing_id'), 'referral_tracks', ['listing_id'], unique=False)
    op.create_index(op.f('ix_referral_tracks_referrer_id'), 'referral_tracks', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_referral_tracks_visitor_id'), 'referral_tracks', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_referral_tracks_visitor_ip'), 'referral_tracks', ['visitor_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_tracks_visitor_ip'), table_name='referral_tracks')
    op.drop_index(op.f('ix_referral_tracks_visitor_id'), table_name='referral_tracks')
    op.drop_index(op.f('ix_referral_tracks_referrer_id'), table_name='referral_tracks')
    op.drop_index(op.f('ix_referral_tracks_listing_id'), table_name='referral_tracks')
    op.drop_table('referral_tracks')
    op.drop_index(op.f('ix_edge_points_history_user_id'), table_name='edge_points_history')
    op.drop_table('edge_points_history')
    sa.Enum(name='edge_points_transaction_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

