"""add community auction tables

Revision ID: 50e7a21480b1
Revises: ed33c8d68ba2
Create Date: 2026-05-19 15:43:52.021254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e7a21480b1'
down_revision: Union[str, Sequence[str], None] = 'ed33c8d68ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_auctions',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('min_bid_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_highest_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_bids', sa.Integer(), nullable=False),
    sa.Column('current_winner_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listing_fee_order_id', sa.String(length=255), nullable=True),
    sa.Column('listing_fee_payment_id', sa.String(length=255), nullable=True),
    sa.Column('listing_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('auction_title', sa.String(length=255), nullable=False),
    sa.Column('auction_skills', sa.String(length=1000), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('expected_rate', sa.String(length=255), nullable=True),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name=op.f('fk_community_auctions_community_id_community')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_community_auctions_created_by_users')),
    sa.ForeignKeyConstraint(['current_winner_id'], ['users.id'], name=op.f('fk_community_auctions_current_winner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_auctions'))
    )
    op.create_index(op.f('ix_community_auctions_community_id'), 'community_auctions', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_auctions_created_by'), 'community_auctions', ['created_by'], unique=False)
    op.create_index(op.f('ix_community_auctions_current_winner_id'), 'community_auctions', ['current_winner_id'], unique=False)
    op.create_table('community_auction_bids',
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('bidder_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bid_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('winning_bid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['community_auctions.id'], name=op.f('fk_community_auction_bids_auction_id_community_auctions')),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.id'], name=op.f('fk_community_auction_bids_bidder_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_auction_bids'))
    )
    op.create_index(op.f('ix_community_auction_bids_auction_id'), 'community_auction_bids', ['auction_id'], unique=False)
    op.create_index(op.f('ix_community_auction_bids_bidder_id'), 'community_auction_bids', ['bidder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_auction_bids_bidder_id'), table_name='community_auction_bids')
    op.drop_index(op.f('ix_community_auction_bids_auction_id'), table_name='community_auction_bids')
    op.drop_table('community_auction_bids')
    op.drop_index(op.f('ix_community_auctions_current_winner_id'), table_name='community_auctions')
    op.drop_index(op.f('ix_community_auctions_created_by'), table_name='community_auctions')
    op.drop_index(op.f('ix_community_auctions_community_id'), table_name='community_auctions')
    op.drop_table('community_auctions')
    # ### end Alembic commands ###
