"""create venture views table

Revision ID: a4606a3fab70
Revises: 07803b6e2462
Create Date: 2026-05-13 16:11:19.053143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4606a3fab70'
down_revision: Union[str, Sequence[str], None] = '07803b6e2462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venture_views',
    sa.Column('venture_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=True),
    sa.Column('viewer_industry', sa.String(length=100), nullable=True),
    sa.Column('viewer_role', sa.String(length=100), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name=op.f('fk_venture_views_viewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venture_views'))
    )
    op.create_index('idx_venture_views_venture_id', 'venture_views', ['venture_id'], unique=False)
    op.create_index('idx_venture_views_viewed_at', 'venture_views', ['viewed_at'], unique=False)
    op.create_index('idx_venture_views_viewer_id', 'venture_views', ['viewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_venture_views_viewer_id', table_name='venture_views')
    op.drop_index('idx_venture_views_viewed_at', table_name='venture_views')
    op.drop_index('idx_venture_views_venture_id', table_name='venture_views')
    op.drop_table('venture_views')
    # ### end Alembic commands ###
