from enum import Enum


class CommunityIndustry(str, Enum):
    TECH = "TECH"
    TECHNOLOGY = "TECHNOLOGY"
    FINANCE = "FINANCE"
    HEALTHCARE = "HEALTHCARE"
    EDUCATION = "EDUCATION"
    FOOD_AND_BEVERAGE = "FOOD_AND_BEVERAGE"
    ECOMMERCE = "ECOMMERCE"
    RETAIL = "RETAIL"
    REAL_ESTATE = "REAL_ESTATE"
    MEDIA = "MEDIA"
    MANUFACTURING = "MANUFACTURING"
    LOGISTICS = "LOGISTICS"
    AGRICULTURE = "AGRICULTURE"
    OTHER = "OTHER"
